apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentic-orchestration
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole-nodes.yaml
  - deployment.yaml
  - service.yaml
