apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentic-run-store
  namespace: agentic-orchestration
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: agentic-run-store-hostpath
  volumeName: agentic-run-store-hostpath
  resources:
    requests:
      storage: 10Gi
